# Generated by Django 3.0.3 on 2020-02-08 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='description')),
                ('attachment', models.FileField(upload_to='')),
                ('assigned_to', models.ManyToManyField(related_name='assignees', to='account.User')),
                ('poster', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='account.User', verbose_name='Poster')),
                ('tags', models.ManyToManyField(related_name='ticket_tags', to='project.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, verbose_name='display name')),
                ('admins', models.ManyToManyField(related_name='project_admins', to='account.User')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='account.User', verbose_name='Owner')),
            ],
        ),
    ]
