# Generated by Django 3.0.3 on 2020-02-11 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The date before which the ticket is to be completed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[(1, 'Ticket should be completed as soon as possible.'), (2, 'Ticket should be completed quickly.'), (3, 'Ticket should be completed after higher priority tickets.'), (4, 'Ticket should be completed in spare time.')], default=3, max_length=255, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[(1, 'Complete loss of service or a significant feature that is completely unavailable and no workaround exists. It does not include development issues or problems in staging environments.'), (2, 'Partial loss of service with severe impact on the business and no workaround exists.'), (3, 'Minor loss of service. The result is an inconvenience, which may require a temporary workaround.'), (4, 'No loss of service. The result does not prevent software operation.')], default=3, max_length=255, verbose_name='severity'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='steps_to_reproduce',
            field=models.CharField(blank=True, max_length=1000, verbose_name='description'),
        ),
    ]
