# Generated by Django 3.0.3 on 2020-02-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200211_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed_date',
            field=models.DateTimeField(blank=True, default='', help_text='The date the ticket was completed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='steps_to_reproduce',
            field=models.CharField(blank=True, max_length=1000, verbose_name='steps_to_reproduce'),
        ),
    ]
