# Generated by Django 3.0.3 on 2020-02-11 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200211_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('resolution_order', models.CharField(max_length=1000, verbose_name='resolution_order')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.Project', verbose_name='Project')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_grouping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.TicketGrouping', verbose_name='Ticket Grouping'),
        ),
    ]
