# Generated by Django 3.0.3 on 2020-02-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_ticket_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='name'),
        ),
    ]
