# Generated by Django 3.0.3 on 2020-02-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200211_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='report_type',
            field=models.CharField(blank=True, choices=[(1, 'Coding Error'), (2, 'Design Error'), (3, 'New Suggestion'), (4, 'Documentation Issue'), (5, 'Hardware Problem'), (6, 'Other')], default=6, max_length=255, verbose_name='report_type'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[(1, 'Ticket Pending'), (2, 'Ticket in Progess'), (3, 'Ticket in Testing'), (4, 'Ticket is Blocked.'), (5, 'Ticket is Completed')], default=1, max_length=255, verbose_name='status'),
        ),
    ]
