# Generated by Django 3.0.3 on 2020-02-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200215_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketgrouping',
            name='resolution_order',
            field=models.CharField(blank=True, max_length=1000, verbose_name='resolution_order'),
        ),
    ]
